version: '3'
services:
  solr:
    build:
      context: ./solr
    image: solr:latest
    ports:
     - "8983:8983"
    command: solr-create -p 8983 -c archivesspace -d archivesspace
  db:
    image: mysql:8.0
    command: --character-set-server=UTF8MB4 --innodb_buffer_pool_size=2G --innodb_buffer_pool_instances=2 --log_bin_trust_function_creators=1
    ports:
      - "3306:3306"
    env_file:
      - .env.docker.db