name: Setup ArchivesSpace and optional plugin
description: Checks out version of ArchivesSpace and an optional plugin
inputs:
  archivesspace-version:
    description: Target ArchivesSpace version
    required: true
  db-port:
    description: Port of test db
    required: false
  plugin:
    description: Optional plugin to checkout and add to config
    required: false
  solr-enabled:
    description: Is solr enabled?
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version || 11 }}
        distribution: temurin

    - name: Allow ArchivesSpace functions for app db user
      if: ${{ inputs.db-port }}
      shell: bash
      run: |
        mysql --host 127.0.0.1 --port ${{ inputs.db-port }} -uroot -proot -e "SET GLOBAL log_bin_trust_function_creators = 1;"

    - name: Checkout ArchivesSpace
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.archivesspace-version }}
        repository: Smithsonian/archivesspace
    
    - name: Copy solr config from workspace to solr service
      if: ${{ inputs.solr-enabled }}
      shell: bash
      env:
        SOLR_ID: ${{ job.services.solr.id }}
      run: |
        docker cp solr $SOLR_ID:/solr_conf_from_repo
  
    - name: Create ArchivesSpace Solr core
      if: ${{ inputs.solr-enabled }}
      shell: bash
      env:
        SOLR_ID: ${{ job.services.solr.id }}
      run: |
        docker exec --tty $SOLR_ID solr create_core -p 8983 -c archivesspace -d /solr_conf_from_repo
  
    - name: Checkout plugin
      if: ${{ inputs.plugin }}
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.plugin }}

    - name: Copy plugin to ArchivesSpace and add to config
      if: ${{ inputs.plugin }}
      shell: bash
      run: |
        cp -r ${{ github.workspace }}/${{ inputs.plugin }} ${{ github.workspace }}/plugins
        cd ./common/config/
        touch config.rb
        echo "AppConfig[:plugins] = ['${{ inputs.plugin }}']" > config.rb
